### ISSUE TITLE
undefined symbol: _ZN3c1017RegisterOperatorsC1Ev

### ISSUE THREAD

**Issue by AntoinePrv** [conda-forge/pytorch_sparse-feedstock#21]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
When running `python -c import torch_sparse`, I get the error
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../conda/envs/myenv/lib/python3.8/site-packages/torch_sparse/__init__.py", line 12, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File ".../conda/envs/myenv/lib/python3.8/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File ".../conda/envs/myenv/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: .../conda/envs/myenv/lib/python3.8/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c1017RegisterOperatorsC1Ev
```

I believe this is related to #13 .

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /local_workspace/proant/local/share/conda/envs/myenv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
ampl-mp                   3.1.0             h616b090_1004    conda-forge
ase                       3.21.1             pyhd8ed1ab_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cffi                      1.14.5           py38ha65f79e_0    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
coverage                  5.5              py38h497a2fe_0    conda-forge
cppad                     20210000.6           h9c3ff4c_0    conda-forge
cryptography              3.4.7            py38ha5dfef3_0    conda-forge
cudatoolkit               11.2.2               he111cf0_8    conda-forge
cudnn                     8.1.0.77             h90431f1_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 5.0.7              pyhd8ed1ab_0    conda-forge
ecole                     0.6.0            py38h249d0e6_0    conda-forge
flask                     1.1.2              pyh9f0ad1d_0    conda-forge
fmt                       7.1.3                h0efe328_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py38h578d9bd_3    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
googledrivedownloader     0.4                pyhd3deb0d_1    conda-forge
h5py                      3.2.1           nompi_py38h9915d05_100    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipopt                     3.13.4               h7ede334_0    conda-forge
isodate                   0.6.0                      py_1    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
keepalive                 0.5              py38h578d9bd_5    conda-forge
kiwisolver                1.3.1            py38h1fd1430_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libcurl                   7.76.1               hc4aaa36_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.15.8               h780b84a_0    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libtiff                   4.2.0                hdc55705_1    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
llvm-openmp               11.1.0               h4bd325d_1    conda-forge
llvmlite                  0.36.0           py38h4630a5e_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
magma                     2.5.4                h6103c52_2    conda-forge
markupsafe                1.1.1            py38h497a2fe_3    conda-forge
matplotlib-base           3.4.1            py38hcc49a3a_0    conda-forge
metis                     5.1.0             h58526e2_1006    conda-forge
mkl                       2020.4             h726a3e6_304    conda-forge
more-itertools            8.7.0              pyhd8ed1ab_1    conda-forge
mumps-include             5.2.1               ha770c72_10    conda-forge
mumps-seq                 5.2.1               h47a8eb5_10    conda-forge
nccl                      2.9.6.1              hdc17891_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.5                        py_0    conda-forge
ninja                     1.10.2               h4bd325d_0    conda-forge
numba                     0.53.1           py38h0e12cce_0    conda-forge
numpy                     1.20.2           py38h9894fe3_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hf7af979_0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.4            py38h1abd341_0    conda-forge
pillow                    8.1.2            py38ha0e1e83_1    conda-forge
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py38h578d9bd_4    conda-forge
plyfile                   0.7.4              pyhd8ed1ab_0    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
pytest                    6.2.4            py38h578d9bd_0    conda-forge
pytest-cov                2.11.1             pyh44b312d_0    conda-forge
python                    3.8.8           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.8.0           cuda112py38h3bc52bc_1    conda-forge
pytorch-gpu               1.8.0           cuda112py38h0bbbad9_1    conda-forge
pytorch_cluster           1.5.4            py38h9235441_1    conda-forge
pytorch_geometric         1.6.1              pyh9f0ad1d_0    conda-forge
pytorch_scatter           2.0.6            py38he8ac336_1    conda-forge
pytorch_sparse            0.6.3            py38h9235441_1    conda-forge
pytorch_spline_conv       1.2.0            py38h9235441_1    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
rdflib                    5.0.0            py38h578d9bd_3    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
scikit-learn              0.24.2           py38hdc147b9_0    conda-forge
scip                      7.0.2                h9e5b675_5    conda-forge
scipy                     1.6.3            py38h7b17777_0    conda-forge
scotch                    6.0.9                h0eec0ba_1    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h7f98852_1    conda-forge
sparqlwrapper             1.8.5           py38h578d9bd_1005    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
tbb                       2020.2               h4bd325d_4    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38h497a2fe_1    conda-forge
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : myenv
    active env location : /local_workspace/proant/local/share/conda/envs/myenv
            shell level : 2
       user config file : /home/proant/.condarc
 populated config files : /home/proant/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages : __cuda=11.0
                          __glibc=2.17
       base environment : /home/x86_64-unknown-linux_ol7-gnu/anaconda-2020.07  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /local_workspace/proant/cache/conda/pkgs
       envs directories : /local_workspace/proant/local/share/conda/envs
                          /home/proant/.conda/envs
                          /home/x86_64-unknown-linux_ol7-gnu/anaconda-2020.07/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.8.3 Linux/3.10.0-1127.19.1.el7.x86_64 ol/7.8 glibc/2.17
                UID:GID : 830473770:830473770
             netrc file : None
           offline mode : False
```
</details>

**Comment by Wes-V3** [comment]
I got the same problem and solve it by reinstall pytorch through pip instead of conda.
My CUDA version is 11.2, but there seems no suitable version for this. So I choose the 11.1 version to install.
I have pasted my solution there for your reference.
`pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

wget https://data.pyg.org/whl/torch-1.9.0%2Bcu111/torch_cluster-1.5.9-cp38-cp38-linux_x86_64.whl
wget https://data.pyg.org/whl/torch-1.9.0%2Bcu111/torch_scatter-2.0.7-cp38-cp38-linux_x86_64.whl
wget https://data.pyg.org/whl/torch-1.9.0%2Bcu111/torch_sparse-0.6.10-cp38-cp38-linux_x86_64.whl

pip install torch_cluster-1.5.9-cp38-cp38-linux_x86_64.whl
pip install [torch_scatter-2.0.7-cp38-cp38-linux_x86_64.whl](https://data.pyg.org/whl/torch-1.9.0%2Bcu111/torch_scatter-2.0.7-cp38-cp38-linux_x86_64.whl)
pip install torch_sparse-0.6.10-cp38-cp38-linux_x86_64.whl
pip install torch_geometric`

**Comment by hmaarrfk** [comment]
We weren't so good at pinning pytorch correctly before. Please see if the issue persist if you add the constraint of `"pytorch>=1.11.0"` if it does, we would need to patch the repodata to really pin other builds as incompatible with pytorch 1.11.0

I think we finally got 1.11.0 correct.

**Comment by sorenwacker** [comment]
I installed it with conda/mamba

```
conda install -c pytorch pytorch
conda install -c conda-forge pytorch_geometric
```

I was trying to run some code from a GitHub repo. Turned out I had to use a different versions anyway. So, I am not facing that error anymore. I was just reporting, because installing `1.11` did not solve it for me.

**Comment by hmaarrfk** [comment]
Mixing channels is simply something that we can't support. 

So if you use the pytorch channel, you should talk to them.

We provide pytorch packages on conda-forge which should help you get going.
